server:
  port: 8080

spring:
  application:
    name: banking
  main:
    web-application-type: reactive

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flip:
  token: ${TOKEN_ID}
  payment-gateway-id: ${PAYMENT_GATEWAY_ID}

pg:
  transaction:
    url: http://localhost:8083