package com.core.banking.enums;

public enum SavingTransactionType {
    DEPOSIT, WITHDRAWAL, TRANSFER_IN, TRANSFER_OUT, INTEREST_CREDIT, FEE_DEBIT, INITIAL_DEPOSIT, TRANSFER_INTERBANK_DEBIT,
    FEE_INTERBANK_DEBIT, TRANSFER_INTERNAL_DEBIT, TRANSFER_INTERNAL_CREDIT
}
