package com.core.banking.utils.exception;

public enum GlobalErrorMapping {
    SYSTEM_ERROR("-1", "Error silahkan kontak tim kami"),
    SUCCESS("0", "SUCCESS"),
    ERROR("1", "ERROR"),
    DATA_NOT_FOUND_CUSTOM("IEG-0011", "Data ${1} tidak ditemukan. Pastikan Value yang anda masukan sudah sesuai"),
    DATA_NOT_FOUND("IEG-0012", "Data tidak ditemukan. Pastikan Value yang anda masukan sudah sesuai"),
    RULE_NOT_FOUND("IEG-0013", "Data RULE tidak ditemukan. Pastikan Value yang anda masukan sudah sesuai"),
    STOCK_NOT_FOUND("IEG-0015", "Stock tidak ditemukan."),
    CASHIER_NOT_FOUND("IEG-0016", "Data Cashier ID tidak ditemukan. Pastikan cashier id yang anda masukan sesuai dengan kondisi di database."),
    PRODUCT_STOCK_NOT_ENOUGH("IEG-0017", "Stock product yang dipilih, saat ini stock product tersebut kurang dari quantity. Data Product Stock tidak dapat memenuhi permintaan pelanggan."),
    PRODUCT_ID_NOT_FOUND("IEG-0018", "Data Product ID tidak ditemukan. Pastikan product id yang anda masukan sesuai dengan kondisi di database"),
    NOMINAL_NOT_ENOUGH("IEG-0019", "Uang pelanggan kurang. Pelanggan tidak dapat membayar harga satuan produk, dikali quantity."),
    DATA_USER_NOT_FOUND("IEG-0020", "Data USER tidak ditemukan. Pastikan Value yang anda masukan sudah sesuai"),
    INVALID_CREDENTIAL("IEG-0021", "Username atau password salah."),
    DATA_ALREADY_EXIST("IEG-0023", "Data ditemukan. Pastikan data yang anda masukan belum terdaftar"),
    INSUFFICIENT_AGE("IEG-0024", "Umur harus lebih dari 17 tahun"),
    CUSTOMER_INACTIVE("IEG-0025", "Tidak bisa memperbaharui data customer, silakan melakukan update status terlebih dahulu"),
    EMAIL_ALREADY_EXIST("IEG-0026", "Email ditemukan. Pastikan email yang anda masukan belum terdaftar"),
    PHONE_ALREADY_EXIST("IEG-0027", "Nomor Telepon ditemukan. Pastikan nomor yang anda masukan belum terdaftar"),
    NOT_FOUND_ID("IEG-0028", "Data ID Tidak Ditemukan"),
    ACCOUNT_CLOSE_RESTRICTED("IEG-0029", "Rekening tidak dapat ditutup karena masih terdapat data tabungan atau pinjaman yang aktif"),
    ESCROW_ACCOUNT_DETAIL_ID_NOT_FOUND("IEG-0030", "ID Escrow account detail tidak ditemukan"),
    PAYER_CUSTOMER_NOT_FOUND("IEG-0031", "Payer customer tidak ditemukan"),
    BENEFICIARY_CUSTOMER_NOT_FOUND("IEG-0032", "Beneficiary customer tidak ditemukan"),
    TRANSACTION_TYPE_INVALID_OR_NULL("IEG-0033","Transaction type tidak valid atau tidak tersedia"),
    SAVING_ACCOUNT_NOT_FOUND("IEG-0034", "Saving account tidak ditemukan"),
    LOAN_ACCOUNT_NOT_FOUND("IEG-0035", "Loan account tidak ditemukan"),
    DEPOSIT_ACCOUNT_NOT_FOUND("IEG-0036", "Deposit account not found"),
    ESCROW_ACCOUNT_NOT_FOUND("IEG-0037", "Escrow account tidak ditemukan"),
    TRANSACTION_NOMINAL_INVALID("IEG-0038", "Nominal transaksi harus lebih dari nol"),
    ESCROW_STATUS_NOT_PENDING_FUNDING("IEG-0039", "Status escrow harus PENDING_FUNDING"),
    FUNDING_SHOULD_NOT_HAVE_RELEASE_ACCOUNT("IEG-0040", "Transaksi dalam status FUNDING tidak boleh memiliki release account number"),
    RELEASE_ACCOUNT_NUMBER_REQUIRED("IEG-0041", "Release account number wajib diisi untuk melakukan transaksi, mengubah status menjadi RELEASE"),
    ESCROW_STATUS_NOT_FUNDED("IEG-0042", "Status escrow account harus FUNDED untuk melakukan transaksi, mengubah status menjadi RELEASE atau RETURN"),
    ESCROW_BALANCE_NOT_ENOUGH("IEG-0043", "Saldo escrow account tidak mencukupi untuk melakukan transaksi"),
    ESCROW_TRANSACTION_TYPE_INVALID("IEG-0044", "Jenis transaksi escrow tidak valid atau tidak didukung"),
    CLOSED_ACCOUNT_FAILED("IEG-0045", "Cannot close account with non-zero balance."),
    DORMANT_ACCOUNT_FAILED("IEG-0046", "Cannot mark a CLOSED account as DORMANT."),
    BLOCK_ACCOUNT_FAILED("IEG-0047", "Cannot BLOCK a CLOSED account."),
    CUSTOMER_NOT_FOUND("IEG-0048", "Customer does not exist."),
    NEGATIVE_INITIAL_DEPOSIT("IEG-0049", "Initial deposit cannot be negative."),
    MINIMUM_INITIAL_DEPOSIT("IEG-0050", "Initial deposit less than minimum."),
    ACCOUNT_NUMBER_NOT_FOUND("IEG-0051", "Account number not found. Make sure the value you entered is correct."),
    ID_NOT_FOUND("IEG-0052", "ID Tidak ditemukan. pastikan id yang dimasukkan sesuai!."),
    AMOUNT_NOT_ENOUGH("IEG-0053", "Amount tidak sesuai dengan yang telah ditentukan!."),
    CUSTOMER_NOT_ACTIVE("IEG-0054", "Customer tersebut tidak active!."),
    NOMINAL_NOT_ENOUGHT("IEG-0055", "Nominal tidak sesuai dengan yang telah ditentukan!."),
    DURATION_NOT_ENOUGHT("IEG-0056", "Durasi tidak sesuai dengan yang telah ditentukan!."),
    NOT_PENDING_APPROVAL("IEG-0057", "Status bukan PENDING_APPROVAL!."),
    NOT_PENDING("IEG-0058", "Status pembayaran bukan PENDING!."),
    NOT_ACTIVE("IEG-0059", "Status akun tidak ACTIVE!."),
    CUSTOMER_BORROW("IEG-0060", "Customer sudah memiliki pinjaman aktif!."),
    UNAUTHORIZED_ACCESS("IEG-0022", "Akses tidak diizinkan. Anda tidak memiliki hak untuk mengakses resource ini."),
    ACC_NUMBER_REQ("IEG-0028", "Account number diperlukan. Hint: Pastikan account number ada"),
    ACC_NUMBER_EXIST("IEG-0029", "Account number telah ada. Hint: Pastikan masukan account number yang berbeda."),
    DEPOSIT_TYPE_CONFIG_NOT_FOUND("DEP-0003", "Konfigurasi jenis deposito tidak ditemukan. Hint: Cek teliti deposit type config id."),
    DEPOSIT_TYPE_CONFIG_NOT_ACTIVE("DEP-0004", "Konfigurasi jenis deposito tersebut tidak aktif. Hint: Pastikan konfigurasi jenis deposito tersebut berstatus aktif."),
    DEPOSIT_AMOUNT_BELOW_MINIMUM("DEP-0005", "Jumlah setoran/nominal deposit tidak memenuhi nominal dari minimum deposit, juga tidak boleh minus. Hint: Pastikan jumlah setoran/nominal deposit lebih dari minimum deposit."),
    DEPOSIT_ACCOUNT_NOT_ACTIVE("DEP-007", "Akun deposito tersebut tidak aktif. Hint: Pastikan akun deposito tersebut berstatus aktif"),
    DEPOSIT_MATURITY_DATE_NOT_REACHED("DEP-008", "Akun deposito tersebut, tanggal jatuh temponya belum memenuhi. Hint: Cek teliti tanggal jatuh tempo vs tanggal saat ini"),
    INVALID_ROLLOVER_OPTION("DEP-009", "Opsi perpanjangan tidak valid. Hint: Cek teliti opsi perpanjangan yang tersedia."),
    MATURITY_DATE_NOT_REACHED("DEP-010", "Tanggal jatuh tempo belum tercapai. Hint: Periksa kembali tanggal pada opened at dan maturity date."),
    INVALID_DEPOSIT_AMOUNT("IEG-0102", "Jumlah deposit tidak valid. Harus lebih besar dari nol."),
    INVALID_WITHDRAWAL_AMOUNT("IEG-0103", "Jumlah penarikan tidak valid. Harus lebih besar dari nol."),
    INSUFFICIENT_BALANCE("IEG-0104", "Saldo tabungan tidak cukup untuk melakukan penarikan."),
    MAX_BALANCE_EXCEEDED("IEG-0105", "limit transaksi yang telah ditetapkan telah terlampaui"),
    INVALID_DATE_RANGE("IEG-0106", "Tanggal mulai tidak boleh setelah tanggal akhir pernyataan"),
    MISSING_ACCOUNT_ID("IEG-0107", "Saving account ID Diperlukan Untuk Laporan"),
    DAILY_NOMINAL_LIMIT_EXCEEDED("IEG-0108", "melebihi batas nominal transaksi harian"),
    DAILY_COUNT_LIMIT_EXCEEDED("IEG-0109", "melebihi batas pengambilan"),
    ACCOUNT_NOT_ACTIVE("IEG-0110", "Akun tidak aktif"),
    MIN_BALANCE_VIOLATED("IEG-0111", "Kurang dari Saldo Minimal"),
    INVALID_PAGE_PARAM("IEG-0112", "Nomer Page tidak Boleh Negatif"),
    INVALID_PAGE_SIZE_PARAM("IEG-0113","halaman harus 1-100 Halaman"),
    SAVING_CONFIG_NOT_FOUND ("IEG-0114", "Saving Config tidak ditemukan"),
    TRX_REF_GENERATION_FAILED ("IEG-0115", "gagal generate code"),
    ESCROW_ACCOUNT_NOT_FUNDED ("IEG-0116", "Escrow account harus dalam status funded"),
    ESCROW_INSUFFICIENT_BALANCE ("IEG-0117","Dana di escrow akun tidak memadai"),
    TRANSACTION_RECORD_NOT_FOUND ("IEG-118","code transaksi tidak ditemukan"),
    SAVING_ACCOUNT_HAS_TRANSACTION("IEG-0119","Account Sudah Ada Melakukan Transaksi"),
    SOURCE_AND_DESTINATION_CANT_BE_THE_SAME("IEG-120","Rekening Pengirim dan Penerima Tidak Boleh sama");






    public final String code;
    public final String message;

    GlobalErrorMapping(String code, String message) {
        this.code = code;
        this.message = message;
    }
}
